version: '3'

services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '13306:3306'
    volumes:
      - db_data:/var/lib/mysql
  api:
    build: ./docker/api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - EDITOR=vim
    ports:
      - '8000:3000'
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
      #  front:
      #    build: ./docker/front
      #    volumes:
      #      - ./front:/app
      #    ports:
      #      - '8080:8080'
      #    tty: true
      #    stdin_open: true
      #    command: npm run serve

volumes:
  bundle:
  db_data:

