version: '3'

x-rails-base: &rails-base
    build: ./docker/api
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true

services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '13306:3306'
    volumes:
      - db_data:/var/lib/mysql
  api:
    <<: *rails-base
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - EDITOR=vim
      - TZ=Asia/Tokyo
    ports:
      - '23000:3000'
    depends_on:
      - db
  solargraph:
    <<: *rails-base
    command: bundle exec solargraph socket --host=0.0.0.0 --port=7658
    ports:
      - '17658:7658'
    restart: always
  front:
    build: ./docker/front
    volumes:
      - ./front:/nuxt-app
      - n_modules:/nuxt-app/node_modules
    ports:
      - '13000:3000'
    tty: true
    stdin_open: true
    command: npm run dev -- -o
volumes:
  db_data:
  bundle:
  n_modules:
