require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/Lambda:
  EnforcedStyle: literal
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": ()
    "%I": ()
    "%r": ()
    "%w": ()
    "%W": ()
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/RescueStandardError:
  EnforcedStyle: implicit

Layout/LineLength:
  Max: 180
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/MethodLength:
  Max: 15
